### ISSUE TITLE
Update Python to Python3.8

### ISSUE THREAD

**Issue by mvartani76** [mvartani76/RPi-AWS-IoT-GarageDoorOpener#9]
In order to utilize the shared memory features in Python, we need to update the code/environment to be compatible with Python 3.8.

**Comment by mvartani76** [comment]
Running this code
`python3 uart_peripheral.py`
gives this error after installing python3.8

```
Traceback (most recent call last):
  File "uart_peripheral.py", line 2, in <module>
    import dbus, dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus'
```

Resolved with:
```
sudo apt install build-essential libpython3-dev libdbus-1-dev
sudo apt-get install libglib2.0-dev
sudo apt-get install libgtk2.0-dev
sudo python3 -m pip install dbus-python
```

**Comment by mvartani76** [comment]
Running this code
`python3 uart_peripheral.py`
gives this error after installing python3.8

```
Traceback (most recent call last):
  File "uart_peripheral.py", line 3, in <module>
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi'
```

Resolved with:
`sudo python3 -m pip install gi`

**Comment by mvartani76** [comment]
Running this code
`python3 uart_peripheral.py`
gives this error after installing python3.8

```
Traceback (most recent call last):
  File "uart_peripheral.py", line 3, in <module>
    from gi.repository import GLib
  File "/usr/local/opt/python-3.8.0/lib/python3.8/site-packages/gi/__init__.py", line 39
    print url
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(url)?
```
Resolved by changing the __init__.py file to put parentheses around url as shown here
`print(url)`

**Comment by mvartani76** [comment]
Running this code
`python3 uart_peripheral.py`
gives this error after installing python3.8

```
Traceback (most recent call last):
  File "uart_peripheral.py", line 3, in <module>
    from gi.repository import GLib
  File "/usr/local/opt/python-3.8.0/lib/python3.8/site-packages/gi/__init__.py", line 41
    print e.value
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(e.value)?
```
Resolved by changing the init.py file to put parentheses around e.value as shown here
`print(e.value)`

**Comment by mvartani76** [comment]
Running this code
`python3 uart_peripheral.py`
gives this error after installing python3.8

```
Traceback (most recent call last):
  File "uart_peripheral.py", line 3, in <module>
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi.repository'
```

Resolved with:
```
sudo apt-get install libgirepository1.0-dev
sudo python3 -m pip install PyGObject
```

**Comment by mvartani76** [comment]
Running this code
`python3 uart_peripheral.py`
gives this error after installing python3.8

```
Traceback (most recent call last):
  File "uart_peripheral.py", line 8, in <module>
    import RPi.GPIO as GPIO
ModuleNotFoundError: No module named 'RPi'
```

Resolved with:
`sudo python3 -m pip install RPi.GPIO`

**Comment by mvartani76** [comment]
the above check-in fixed the following error:

```
Traceback (most recent call last):
  File "uart_peripheral.py", line 220, in <module>
    main()
  File "uart_peripheral.py", line 192, in main
    adapter = find_adapter(bus)
  File "uart_peripheral.py", line 181, in find_adapter
    for o, props in objects.iteritems():
AttributeError: 'dbus.Dictionary' object has no attribute 'iteritems'
```

**Comment by mvartani76** [comment]
Running this code
`./garage_start.sh`
gives this error after installing python3.8

```
Traceback (most recent call last):
  File "awsiot_garage.py", line 17, in <module>
    from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient
ModuleNotFoundError: No module named 'AWSIoTPythonSDK'
```

Resolved with:
`sudo python3 -m pip install AWSIoTPythonSDK`

**Comment by mvartani76** [comment]
Running this code
`./garage_start.sh`
gives this error after installing python3.8

```
Traceback (most recent call last):
  File "awsiot_garage.py", line 23, in <module>
    import i2c_lcd_driver
  File "/home/pi/Documents/RPi-AWS-IoT-GarageDoorOpener/Python/i2c_lcd_driver.py", line 24, in <module>
    import smbus
ModuleNotFoundError: No module named 'smbus'
```

Resolved with:
`sudo python3 -m pip install smbus`
